### ISSUE TITLE
Naming (profanity)

### ISSUE THREAD

**Issue by stevecoug** [sitexw/FuckAdBlock#17]
I'd like to use this on my production site, but having profanity in the name makes it something I can't justify putting in our production code. Would you consider renaming it in the future?

**Comment by sitexw** [comment]
"Unfortunately", the popularity of the script comes in part (I think) of his name.
It would be a shame to change, especially as he begins to become popular.

It bothers you that much to have that name in your Script?
The end user will never see it and for people who watch the code, it will add a touch of humor.

What is it that bothers you? The file name? The name of the variable?

**Comment by stevecoug** [comment]
Let's just say that the users of my site wouldn't find it so humorous.

**Comment by sitexw** [comment]
The only thing I can advise you to do, is a Fork of the project and then change the filename and variables.

**Comment by SubJunk** [comment]
@stevecoug I would be happy to make the modifications for you if you want since I sympathize with your position

**Comment by stevecoug** [comment]
I just wrote a script that downloads the latest .js file and runs it through sed to modify it

**Comment by SubJunk** [comment]
:+1:

**Comment by sitexw** [comment]
I just created a second version of FuckAdBlock project, [BlockAdBlock](https://github.com/sitexw/BlockAdBlock).
This fork is always updated together FuckAdBlock.

**Comment by stevecoug** [comment]
Thank you, I appreciate it.

**Comment by sitexw** [comment]
No problem.
