### ISSUE TITLE
Adblock passed with avast online security chrome extension

### ISSUE THREAD

**Issue by ryush00** [sitexw/FuckAdBlock#19]
https://chrome.google.com/webstore/detail/avast-online-security/gomekmidlodglbbmalcneegieacbdmki

**Comment by sitexw** [comment]
Hello, I don't understand the problem.
Thank you to give me a little more information.

**Comment by ryush00** [comment]
When using that extension, Ads is blocked without detect adblock.

**Comment by sitexw** [comment]
I installed the extension of Avast and I go on http://sitexw.fr/fuckadblock/. But it is detecting AdBlock.
Can you give me information on your config (OS, browser, ...), sample urls or even a sample code (on jsfiddle.net).

Thank you.

**Comment by ryush00** [comment]
![ad](https://cloud.githubusercontent.com/assets/4997174/7894803/5d2ec9a2-06ac-11e5-8a5a-2d2ebfe2e393.png)

It block ad-network's address.

![screenshot_1](https://cloud.githubusercontent.com/assets/4997174/7894811/8ee49be8-06ac-11e5-82b3-142f9f67f79c.png)

So, if it is real ad, user can block the addresss without detection.

**Comment by sitexw** [comment]
Ok, I'll watch that.
But I think that to detect this, it will make an HTTP request. This is a similar subject for the detection method:
https://github.com/sitexw/FuckAdBlock/issues/18
