### ISSUE TITLE
Breaks if using jQuery .submit() hook?

### ISSUE THREAD

**Issue by DarkAgent2005** [sitexw/FuckAdBlock#20]
I have the following code:

    <script type="text/javascript" src="blockadblock.js"></script>
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <form method="POST" id="myform" action="http://example.com" data-ajax="false" target="_blank">
    <input name="email" type="text"><input id="submit" type="submit" value="submit"></form>
    <script>
    function adBlockNotDetected() {
        alert('AdBlock is not enabled');
    }
    function adBlockDetected() {
        alert('AdBlock is enabled');
    }
    jQuery(function() {
        jQuery('#myform').on('submit', function(e) { 
    		e.preventDefault();
    		var d = new Date();
		alert('Step 1');
		if(typeof blockAdBlock === 'undefined') {
			adBlockDetected();
			alert('Step 2');
		} else {
			blockAdBlock.onDetected(adBlockDetected);
			blockAdBlock.onNotDetected(adBlockNotDetected);
			alert('Step 3');
		}
		alert('Step 4');
        });
    });
    </script>

The idea is to check if ads are blocked upon form submit. The jQuery form submit hook seems to work just fine -- `var d = new Date()`; executes as expected. Furthermore, `alert('Step 1');` `alert('Step 3');` and `alert('Step 4');` execute as expected. However, the code after that does not execute (i.e. the ad block checking and related alerts)... and I'm not sure why. What is baffling is, the following works just fine -- it shows the proper alerts as expected:

    <script type="text/javascript" src="blockadblock.js"></script><script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <script>
    function adBlockNotDetected() {
        alert('AdBlock is not enabled');
    }
    function adBlockDetected() {
        alert('AdBlock is enabled');
    }
    jQuery(function() {
    	if(typeof blockAdBlock === 'undefined') {
    		adBlockDetected();
    	} else {
    		blockAdBlock.onDetected(adBlockDetected);
    		blockAdBlock.onNotDetected(adBlockNotDetected);
    	}
    });
    </script>

What is going on? Why isn't the first block of code working? Thanks!

**Comment by sitexw** [comment]
For my part, I tried that : https://jsfiddle.net/sitexw/kwyd02vv/3/embedded/result/
And AdBlock is activated or not, the two scripts work.

**Comment by DarkAgent2005** [comment]
Is the line "blockAdBlock.check();" the reason why it worked when you tried it?

**Comment by sitexw** [comment]
Yes, the `check()` method lets look again if AdBlock is activated and this triggers the events `onNotDetected` or `onDetected`.

Optional:
By default, after each `check()` (even at the default page loads) the events list is emptied. To disable the automatic emptying of events, change the option as follows: `blockAdBlock.setOption('resetOnEnd', false)`. This can be useful to you for not having to redeclare the events every time:
```javascript
if(typeof blockAdBlock !== 'undefined') {
	blockAdBlock.setOption('resetOnEnd', false);
	blockAdBlock.onDetected(adBlockDetected);
	blockAdBlock.onNotDetected(adBlockNotDetected);
}
jQuery('#myform').on('submit', function(e) { 
	e.preventDefault();
	if(typeof blockAdBlock !== 'undefined') {
		blockAdBlock.check();
	} else {
		adBlockDetected();
	}
});
```

**Comment by DarkAgent2005** [comment]
Ah, okay, thank you for that!

**Comment by DarkAgent2005** [comment]
Question. Is it possible to do a simple if statement to check if ads are blocked, instead of blockAdBlock.onDetected(adBlockDetected) and blockAdBlock.onNotDetected(adBlockNotDetected)?

**Comment by DarkAgent2005** [comment]
If I run blockAdBlock in an iFrame, is there any way to check if ads are blocked on the parent URL domain instead of iFrame domain (assuming the two are different)?

**Comment by sitexw** [comment]
Oui et non.
Non, car ce n'est pas prévu dans le script (et en plus il faut un peu de temps pour détecter AdBlock).
Oui, car vous pouvez le faire plus ou moins vous-même :
```javascript
var adBlockIsDetected = false;
blockAdBlock.onDetected(function() {
    adBlockIsDetected = true;
});
jQuery('#myform').on('submit', function(e) {
    if(adBlockIsDetected === true) {
        alert('AdBlock enable');
    } else {
        alert('AdBlock not enable');
    }
});
```
