### ISSUE TITLE
A fork of your library without attribution?

### ISSUE THREAD

**Issue by bjornstar** [sitexw/FuckAdBlock#21]
I was reading arstechnica this morning and noticed it was loading [a fork of this library with no attribution] (https://github.com/veeracs/SniffAdBlock). A huge company like [Condé Nast](http://en.wikipedia.org/wiki/Cond%C3%A9_Nast) should know better than to use a library without proper attribution. Especially considering how much they complain about people reading their website for free.

http://assets.adobedtm.com/6372cf21ef88ee60bc2977a4898dcb5c7945a212/scripts/satellite-554bd3ed3231390014de0700.js

http://assets.adobedtm.com/6372cf21ef88ee60bc2977a4898dcb5c7945a212/scripts/satellite-554bd4186631632069aa0300.js

@veeracs should not have removed the attribution at the top of the main library file. Considering you recently made sitexw/BlockAdBlock he should either start using that or provide proper attribution in his fork.

I would suggest you update your LICENSE file to make the copyright based on your name and e-mail address. I will post in the Ars Forums to try to get them to use sitexw/BlockAdBlock with proper attribution.

**Comment by sitexw** [comment]
Okay great, thank you.
Can you give me an example of the change that I do?

**Comment by bjornstar** [comment]
Currently, your LICENSE.md file says:

`Copyright (c) 2015 FuckAdBlock`

I suggest you change it match what you have in your package.json/bower.json:
`Copyright (c) 2015 Valentin Allaire <valentin.allaire@sitexw.fr>`

I also recommend you change the comments at the beginning of your library file to the same copyright line and mention the MIT License:

``` javascript
/*
 * Copyright (c) 2015 Valentin Allaire <valentin.allaire@sitexw.fr>
 * Released under the MIT license
 * https://github.com/sitexw/FuckAdBlock
 */
```

I can send a PR if you'd prefer that.

You should also contact @veeracs and ask him to either switch to using sitexw/BlockAdBlock or attribute his fork properly.

**Comment by sitexw** [comment]
Ok, I'll make the changes but I ask myself a question:
For the change to be visible to all (npm, bower, ...), do I create a new version number? In my case, the v3.1.1? Or stay on v3.1.0?

**Comment by bjornstar** [comment]
You'll need to release a new version, 3.1.1 sounds like a good idea since it's basically a documentation change.

For forks, typically you would specify the original copyright, and then add your own copyright specifically for modifications.

It looks like [Ars is going to update their copy](http://arstechnica.com/civis/viewtopic.php?f=3&t=1284249&p=29117417#p29117417) to include attribution, hopefully they'll use your new version.

**Comment by sitexw** [comment]
Je fis les changements. Pouvez-vous me dire si cela sonne juste?

**Comment by bjornstar** [comment]
Looks great! Thanks for doing that.
