### ISSUE TITLE
Add "Do Not Track" detection for Firefox?

### ISSUE THREAD

**Issue by timbowhite** [sitexw/FuckAdBlock#30]
Firefox has a [tracking protection feature](https://support.mozilla.org/en-US/kb/tracking-protection-firefox) that seems to have recently started blocking things like Google Adsense, Analytics, etc.  It's based on [Disconnect's blocklist](https://disconnect.me/).  AFAIK, Firefox is the only major browser that actually blocks requests based on this setting, whereas other browsers only send the DNT header.

Would it be within the scope of this project to also detect "Do Not Track" for Firefox users? Detection should be easy:

```javascript
if(navigator.userAgent.toLowerCase().indexOf('firefox') !== -1 && navigator.doNotTrack){
  // DNT enabled
}
```

FuckAdBlock doesn't seem to pick up on Firefox DNT blocking.  I've got it installed at http://proxyrox.com if you want to test - should display a big "Ad Blocking Software Detected" when blocking is detected.

**Comment by MESWEB** [comment]
Waterfox 64 too.

**Comment by timbowhite** [comment]
Well I dug a bit deeper.  Turns out Firefox's Do No Track and tracking protection are two separate things:

1. [https://www.mozilla.org/en-US/firefox/dnt/](Do Not Track) is enabled in Preferences/Options > Privacy > "Tell sites that I do not want to be tracked".  Enabling sends the DNT header but it _does not_ block any requests.
2. [https://support.mozilla.org/en-US/kb/tracking-protection-firefox](Tracking Protection) is enabled in about:config > privacy.trackingprotection.enabled.  Enabling does not send the DNT header, but _does_ block requests based on Disconnect's blocklist.

So detecting 2 isn't as easy as checking ```navigator.doNotTrack```, because that property is only set for 1.

But, I was able to successfully detect FF tracking protection by checking to see if the "googlesyndication.com" domain is blocked (it's the domain that adsense JS is served from) by using a hidden iframe:

```html
<iframe src="//googlesyndication.com" onload="console.log('FF tracking protection disabled')" style="width: 1px !important; height: 1px !important; position: absolute !important; left: -10000px !important; top: -1000px !important;"></iframe>
```

The ```onload``` event won't fire if tracking protection is enabled, but it will when it's disabled, even if the iframe won't load due to X-Frame-Options:

> Load denied by X-Frame-Options: https://www.google.com/?gws_rd=ssl does not permit cross-origin framing.

So that's one way to detect FF tracking protection, though it's a bit clunky.  Let me know if there's any demand to make a pull request for this to FAB.

PS As a side note, when adsense is blocked, the FF console will issue a warning like this:

> The resource at "http://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js" was blocked because tracking protection is enabled.

**Comment by sitexw** [comment]
Hello, I found it all pretty interesting, but the question is: Is this kind of detection has its place here?
This is not an aggressive question, but simply to discuss this feature and if it is interesting and asked by users FuckAdBlock.

**Comment by timbowhite** [comment]
> Is this kind of detection has its place here?

Yeah, I don't know.  Might be best to keep this issue open and see if other users have any interest in it.

If it were to be implemented, I think it'd be best to make it an option, ie.:

```javascript
fuckAdBlock.setOption({
  detectTrackingProtection: true
});
```

**Comment by sitexw** [comment]
>If it were to be implemented, I think it'd be best to make it an option, ie.:
>
>```javascript
>fuckAdBlock.setOption({
>  detectTrackingProtection: true
>});
>```
I agree with this point

>Is this kind of detection has its place here?
For if we implement this feature and that AdBlock is enabled, the file 'fuckAdBlock.js is then blocked, so we can not access the traking detection system, and therefore we can not consider that the "blocking traking" is enabled, the pretext that AdBlock blocks the script.
(I hope that the translation is understandable ^^)

**Comment by timbowhite** [comment]
> For if we implement this feature and that AdBlock is enabled, the file 'fuckAdBlock.js is then blocked, so we can not access the traking detection system, and therefore we can not consider that the "blocking traking" is enabled, the pretext that AdBlock blocks the script.
(I hope that the translation is understandable ^^)

Yes I understand.  I think for most cases, it won't matter - most FAB users would probably only care if there is any kind of ad blocking going on at all (not just specifically Firefox tracking protection vs. Adblock).
