### ISSUE TITLE
Please block AdsBypasser script

### ISSUE THREAD

**Issue by Melhosh** [sitexw/FuckAdBlock#31]
Hello

Could you please update your file to blocks AdsBypasser script,
You can find this script in the following link:
https://greasyfork.org/en/scripts/4881-adsbypasser

**Comment by sitexw** [comment]
Hello, you concrete examples of blocked site?
Because the only one I've seen is AdFly. That such a script that will detect "AdsBypasser" on AdFly:
```javascript
if(window.cookieCheck !== undefined && window.close_bar !== undefined && window.eu !== undefined) {
	console.log('DETECTED');
} else {
	console.log('NOT DETECTED');
}
```

**Comment by Melhosh** [comment]
Hello,
I am not sure if I have understood you,
anyway, if you visit this link: http://al.ly/LCsk
you will notice that  AdsBypasser will block the ads in iframe tag.

**Comment by sitexw** [comment]
Ok, I understand better.
For you, this is the script that is used to block you via "AdsBypasser":
```javascript
$.register({
  rule: {
    host: /^al\.ly$/,
  },
  ready: function () {
    'use strict';
    $.removeNodes('iframe');
    var a = $('#close');
    a.disabled = false;
    a.click();
  },
});
```

We can observe that the blocking his written scripts customized for each site. It is therefore not possible to generalize FuckAdBlock detection.
In your case, a simple check on the existence of your iframe will do. That is to say if you create 3 iframe on loading of the page and a few milliseconds later, he not exists, then AdsBypasser (or other) passed by there.

I have observed that you use FuckAdBlock but you had completely renamed. I find that not nice ... But, it is MIT.

**Comment by Melhosh** [comment]
Sorry for renamed, but I do that because to avoid "Anti-Adblock Killer"..
Anyway, could you please write to me a script that will solve my issue
