### ISSUE TITLE
Adblock plus bypass your script

### ISSUE THREAD

**Issue by mballag** [sitexw/FuckAdBlock#32]
When I try to add the following two filters to Adblock plus:
@@||sitexw.fr^$script

@@||sitexw.fr^$elemhide

Then will bypass your script As you can see in attached image.
Could you please fix this as soon as possible..
![2015-10-11_10-47-55](https://cloud.githubusercontent.com/assets/15073079/10416072/f4d6d836-7005-11e5-8ecd-8e01d5b49a63.png)

**Comment by sitexw** [comment]
It is a real question?
For your Github account has been created together with the issue.

**Comment by Melhosh** [comment]
Yes, I have create an account to getting your help to solve this issue only,

**Comment by mballag** [comment]
Hello,
So, there is no solution for this issue??

**Comment by mballag** [comment]
Excuse me,
please explain what did you mean that my account caused this issue.

**Comment by mballag** [comment]
I will donate to you, if you helped me to solve this issue

**Comment by sitexw** [comment]
I'll answer the question, but the subject remains strange.

FuckAdBlock is designed to detect an ad blocker in action and not to detect if an advertisement blocking extension is present.
That is to say that if advertisement blocking extension (eg AdBlock) is on the browser, but that there is an exception to the site, FuckAdBlock can not detect it because the ad blocker does not block ads..

**Comment by Melhosh** [comment]
The Adblock block the ads, and FuckAdBlock can not detect it..

Did you tried to ad the following two codes to you Adblock plus filter and test your script again:
<pre>@@||sitexw.fr^$script</pre>
<pre>@@||sitexw.fr^$elemhide</pre>

You will understand me

**Comment by mballag** [comment]
The Adblock block the ads, and FuckAdBlock can not detect it..

Did you tried to ad the following two codes to you Adblock plus filter and test your script again:

<pre>@@||sitexw.fr^$script</pre>
<pre>@@||sitexw.fr^$elemhide</pre>
You will understand me

**Comment by Melhosh** [comment]
The Adblock block the ads, and FuckAdBlock can not detect it..

Did you tried to ad the following two codes to you Adblock plus filter and test your script again:

<pre>@@||sitexw.fr^$script</pre>
<pre>@@||sitexw.fr^$elemhide</pre>
You will understand me

**Comment by Melhosh** [comment]
The Adblock block the ads, and FuckAdBlock can not detect it..

Did you tried to ad the following two codes to you Adblock plus filter and test your script again:

<pre>@@||sitexw.fr^$script</pre>
<pre>@@||sitexw.fr^$elemhide</pre>
You will understand me

**Comment by sitexw** [comment]
Ok, I understand better.
I'm sorry, I did not pay attention to "$elemhide".

I am currently working on the V4 FuckAdBlock (#34) and this problem will be resolved.
Thank you.
