### ISSUE TITLE
FuckAdBlock fails when element hiding rules is turned off

### ISSUE THREAD

**Issue by Ellipsis7** [sitexw/FuckAdBlock#33]
Easylist has been adding this exception rule to a lot of domains:

@@||domain.com^$elemhide

Which effectively renders FuckAdBlock useless.

Please, try to work on a fix for this issue.

P.S. Here's the Easylist text which has all the rules and exceptions in it:

https://easylist-downloads.adblockplus.org/easylist.txt

**Comment by sitexw** [comment]
Yes, the problem was already reassembled. Thank you.
I work on V4 (#34) that will solve this problem.
