### ISSUE TITLE
Does not detect Ghostery

### ISSUE THREAD

**Issue by PMcFad** [sitexw/FuckAdBlock#35]
First, great work!  One of the simplest implementations I've seen.  Recently I discovered that the script does not seem to detect Ghostery (https://www.ghostery.com/try-us/download-add-on/).  Any thoughts on how to detect it?

**Comment by sitexw** [comment]
Thank you.
I have seen for "Ghostery", blocking is not automatic and it is targeted by the user.
To detect it, must await the V4 (# 34) that lets you create more precise detection and targeted to certain advertising companies.
I come to you with a sample code in a while.

**Comment by nickygerritsen** [comment]
@sitexw did you already manage to come up with an example for Ghostery for v4 beta?

**Comment by nickygerritsen** [comment]
NVM saw it at #40
