### ISSUE TITLE
Not detecting on certain sites

### ISSUE THREAD

**Issue by simonsez** [sitexw/FuckAdBlock#36]
Hello,

Thanks so much for this plugin, it's really awesome for detecting ad blockers!

I've written a bookmarklet that injects your detector on a page, and unfortunately I've ran into pages that don't seem to have detection working. Here's the code for the bookmarklet:

`javascript:(function() { var fuckAdBlock = false; var el=document.createElement('script');el.type='text/javascript';el.src='http://box.en.io/temp/blockadblock.js';document.getElementsByTagName('head')[0].appendChild(el); setTimeout(function() { myBlockAdBlock = new FuckAdBlock({ checkOnLoad: true, debug: true }); myBlockAdBlock.check(); }, 1000); })();`

I'm running Adblock Plus on Chrome on OSX Yosemite.

Here's an example of it working on www.thedailybeast.com:
```
[FuckAdBlock][setOption] The option "debug" he was assigned to "true"
blockadblock.js:57 [FuckAdBlock][check] An audit was requested with a loop
blockadblock.js:57 [FuckAdBlock][_creatBait] Bait has been created
blockadblock.js:57 [FuckAdBlock][check] A check is in progress ...
blockadblock.js:57 [FuckAdBlock][_checkBait] A check (1/5 ~1ms) was conducted and detection is positive
blockadblock.js:57 [FuckAdBlock][_stopLoop] A loop has been stopped
blockadblock.js:57 [FuckAdBlock][_destroyBait] Bait has been removed
blockadblock.js:57 [FuckAdBlock][emitEvent] An event with a positive detection was called
```

But here it is failing on about.com:
```
[FuckAdBlock][setOption] The option "debug" he was assigned to "true"
blockadblock.js:57 [FuckAdBlock][check] An audit was requested with a loop
blockadblock.js:57 [FuckAdBlock][_creatBait] Bait has been created
blockadblock.js:57 [FuckAdBlock][check] A check is in progress ...
blockadblock.js:57 [FuckAdBlock][_checkBait] A check (1/5 ~1ms) was conducted and detection is negative
blockadblock.js:57 [FuckAdBlock][_checkBait] A check (2/5 ~51ms) was conducted and detection is negative
blockadblock.js:57 [FuckAdBlock][_checkBait] A check (3/5 ~101ms) was conducted and detection is negative
blockadblock.js:57 [FuckAdBlock][_checkBait] A check (4/5 ~151ms) was conducted and detection is negative
blockadblock.js:57 [FuckAdBlock][_checkBait] A check (5/5 ~201ms) was conducted and detection is negative
blockadblock.js:57 [FuckAdBlock][_stopLoop] A loop has been stopped
blockadblock.js:57 [FuckAdBlock][_destroyBait] Bait has been removed
blockadblock.js:57 [FuckAdBlock][emitEvent] An event with a negative detection was called
```

Do you have any idea why the detection might not be working on about.com?

thanks!

**Comment by sitexw** [comment]
Sorry for the response time! My week was a bit long.

I tried your tests and I get the same results. After watching the "EasyList" AdBlock (https://easylist-downloads.adblockplus.org/easylist.txt), it turns out that About.com has several custom filters one of which must disable detection advertisements by HTML. And as FuckAdBlock uses HTML to detect AdBlock, it's normal that does not find so.

To remedy this problem is, it will use the V4 FuckAdBlcok (#34) that uses both the detection by the HTML and HTTP. I tried it and it works on About.com.

Here.

**Comment by simonsez** [comment]
Hello @sitexw thanks so much for this! 

Just so I understand the issue, is it that EasyList is actually removing the calls to the ad URLs on about.com instead of using HTML item removal? And hence the solution is ad some bait URLs which the Adblocker removes?

thanks!

-simon

**Comment by sitexw** [comment]
It is not against the Adblocker because this is AdBlocker himself who sets up these exceptions.
But if not, is that correct.
