### ISSUE TITLE
FuckAdBlock cannot detect Google Chrome Disconnect

### ISSUE THREAD

**Issue by meriken** [sitexw/FuckAdBlock#40]
FuckAdBlock, including the latest beta, cannot detect Google Chrome Disconnect: 
https://chrome.google.com/webstore/detail/disconnect/jeoacafpbcihiomhlakheieifhpjdfeo?utm_source=chrome-app-launcher-info-dialog
![fad](https://cloud.githubusercontent.com/assets/5530653/11458202/4fbb5c50-9670-11e5-9654-7c87c9e9d75d.jpg)

**Comment by sitexw** [comment]
Yes, I know, this is the same "problem" with Ghostery (# 35).

To fix this, you must configure FuckAdBlock accurately as to make the detection possible. You have two options:
- Configure the plugin "http" in "import" mode with the URL of your ad network. So if "Disconnect" (Ghostery, AdBlock ...) block this URL, then they will be detected.
- Using the plugin "Google Adsense" (will happen very soon) and allows rapid detection and dedicate to Google Adsense.

I should add examples in the doc that everyone can do easily.

**Comment by meriken2ch** [comment]
> Configure the plugin "http" in "import" mode with the URL of your ad network.

Ah, I see. This is a new feature in v4:

https://github.com/sitexw/FuckAdBlock/tree/v4.x

I will try this method and get back to you. Thanks!

**Comment by meriken** [comment]
Nope, still no luck with FuckAdBlock (4.0.0-beta.3), Google Chrome 46.0.2490.80 m, and Disconnect 5.18.22 even with the "http" plug-in and an integrity check.

**Comment by sitexw** [comment]
Hello, indeed the HTTP detection is not working.
This is the specific plugin Google Adsense:
```
var FabPluginGoogleAdsense = function() {
	FuckAdBlock.getPluginClass().apply(this, arguments);
	this.options.set({
		windowVar: 'adsbygoogle',
	});

	var data = {};

	this.start = function() {
		var self = this;
		var windowVar = this.options.get('windowVar');
		data.loopTimeout = setTimeout(function() {
			if(window[windowVar].loaded === true) {
				self.callUndetected();
			} else {
				self.callDetected();
			}
		}, 1);
		return this;
	};
	this.stop = function() {
		clearInterval(data.loopTimeout);
		clearInterval(data.loopInterval);
		return this;
	};
};
FabPluginGoogleAdsense.pluginName = 'google-adsense';
FabPluginGoogleAdsense.versionMin = [4, 0, 0];
```
It is temporary and not final, but you can use it.

**Comment by meriken** [comment]
The plug-in works seamlessly. Thanks a lot for the great work! I look forward to the official release of v4.

**Comment by cmstroscio** [comment]
Hello, 

Do you have an example of how to set up to detect ghostery? I started playing around with the fiddle you posted above, but I'm not clear on what needs to be done.
http://jsfiddle.net/cmstroscio/v259sgrz/3/

Thanks!
Marshall

**Comment by sitexw** [comment]
@cmstroscio I took the bases of your code and here is the result:
http://jsfiddle.net/yxn3cL7q/1/
I strongly advise you to add integrity when you import the fuckadblock script. You can see it in my example on line 7. Because the ad blocker has fun modifying the fuckadblock script during the import, to replace it with an inefficient version.

**Comment by cmstroscio** [comment]
@sitexw Thank you so much! I will try this out.
