### ISSUE TITLE
detection problem - firefox 42

### ISSUE THREAD

**Issue by chokopa15** [sitexw/FuckAdBlock#41]
the problem if you add the website to white list or a page to white list adblock still detected as enabled
(disable for this website.. or disable for this page only) adblock still detected as enabled
you should disable adblock completely (disable everywhere) to be detected as not enabled

**Comment by sitexw** [comment]
Personally, I do not have problem with Firefox 42:
http://4.sendvid.com/qo6i8wva.mp4

**Comment by chokopa15** [comment]
firefox 42 + ADP + filtre easy list

<iframe width="853" height="480" src="//sendvid.com/embed/bdzndg9k" frameborder="0" allowfullscreen></iframe>

**Comment by chokopa15** [comment]
my fault. i didn't tell you it's about the v4 beta but i think the video is clear
hope you working on it. cause i didn't got any reply

**Comment by sitexw** [comment]
Ok, I saw the bug and I know where it comes from. (#34)
