### ISSUE TITLE
Name is unprofessional

### ISSUE THREAD

**Issue by Zorlin** [sitexw/FuckAdBlock#42]
I know some of the appeal of FuckAdBlock surely comes from the straightforward name, but I'd like to point out that it's harder for sites to use FuckAdBlock because of the name. No sane website would use it for fear of users finding references to it while browsing around in the source.

Perhaps a different name is in order at some point?

**Comment by shoestar** [comment]
There is a project with a more convenient name at https://github.com/sitexw/BlockAdBlock.
Same code - different name.

**Comment by Zorlin** [comment]
@shoestar That seems a little pointless. Why not just maintain a single project with the more "convenient" name?

**Comment by sitexw** [comment]
Thank you @shoestar.
@Zorlin For it is more eye-catching! Moreover, FuckAdBlock is the base name of the project, all of it is gone. It would be a bit horrible that no longer exists =( ^^
