### ISSUE TITLE
Does not work with uBlock Origin

### ISSUE THREAD

**Issue by TRoskop** [sitexw/FuckAdBlock#44]
Hallo dear Develops.
Your project is not working when using uBlock Origin instead of AdBlock and/or AdBlock Plus.

Your current build, V4 (http://fuckadblock.sitexw.fr/beta/) shows only "Checking...". Nothing else happens. :(

**Comment by TRoskop** [comment]
Edit:
I just created a similar project bases on php and javascript. (But it also supports Javascript-only!)
This project can even work with NoScript-Extensions and with different AdBlockers (like AdBlock Plus and uBlock Origin).

Here the project: > https://github.com/TRoskop/AdDefender
And here are some "Running Examples":
> http://trserver1.site40.net/projects/AdDefender/app-fullbanner.php.html  
> http://trserver1.site40.net/projects/AdDefender/app-smallbanner.php.html

Happy New Year 2016!

**Comment by Daijobou** [comment]
Thanks for your work, but this direction of solution will not work long. When I submit "adwordstracking.js" to the filter as a exlusion. Adblock will work and your message will disappear.

**Comment by Daijobou** [comment]
I think the answer why uBlock not working is here https://github.com/sitexw/FuckAdBlock/issues/54 so this issue can be closed.
