### ISSUE TITLE
Fuck FuckAdBlock

### ISSUE THREAD

**Issue by 2phn0l** [sitexw/FuckAdBlock#45]
AdBlockers are awesome, stop infecting the web with invasive, annoying ads!

**Comment by MESWEB** [comment]
Someone spend time to make context for "you"(and other beggars) and he make's this for free. Did You pay to somebody for browsing his pages? No! Make your own website and feel like to be a volunteer. Any way fu...ck U.

**Comment by Smoke-N-Mirrors** [comment]
> Someone spend time to make context for "you"(and other beggars) and he make's this for free. Did You pay to somebody for browsing his pages? No! Make your own website and feel like to be a volunteer. Any way fu...ck U.

Let me repeat. Any way fu...ck U
