### ISSUE TITLE
New specific rule from adblockplus

### ISSUE THREAD

**Issue by vegagame** [sitexw/FuckAdBlock#48]
Adblock Plus has introduce new filters  that disable generic hiding or blocking rules for a given website whilst leaving site-specific rules intact.

https://adblockplus.org/development-builds/new-filter-options-generichide-and-genericblock

**Comment by sitexw** [comment]
Thanks. Noted.
I think this new rule does not create anything really new. You could already more or less do with it: "$elemhide", "$xmlhttprequest", "$script", ...
But anyway, the V4 will can exposed to this.

Thank you for the news =)
