### ISSUE TITLE
FuckAdBlock script is getting blocked - Failed to load resource: net::ERR_BLOCKED_BY_CLIENT

### ISSUE THREAD

**Issue by slavajacobson** [sitexw/FuckAdBlock#51]
AdBlocker is blocking the page from loading the .JS file with FuckAdBlock. The error message in the browser's console: "Failed to load resource: net::ERR_BLOCKED_BY_CLIENT"

Is there anyway around this?

**Comment by MESWEB** [comment]
Try with dynamic name of script.

**Comment by sitexw** [comment]
Without going that far, simply follow the first sample script on the home :
https://github.com/sitexw/FuckAdBlock
It allows to take into account if the "FuckAdBlock" script is present or not. If it is not present, it means that AdBlock is activated.
