### ISSUE TITLE
False positives due to tracking protection

### ISSUE THREAD

**Issue by e7o-de** [sitexw/FuckAdBlock#60]
Having issues with a site using your "nice" script. Getting a bunch of error messages in Firefox' console saying:

The resource at "..." was blocked because tracking protection is enabled.

Obviosly, your script is not blocked, because the page is complaining about an (imaginary) adblocker. Now, the direct question: Do I have to install an Adblocker to protect me from your crazy script, if it even complains on a Firefox without any extensions installed?

(Btw, I can understand the purpose of not having ads blocked on a page, but providing scripts blocking a built-in tracking protection is not acceptable in any way in a post-Snowden age.)

**Comment by sitexw** [comment]
Hello, I understand your displeasure.

Think you can send me (in private if you want) the URL of the page or site that is the problem?
This will allow me to determine if this is a problem in the script or a problem using the webmaster.

Thank you.

**Comment by e7o-de** [comment]
One page where I noticed it is http://uploaded.net/file/x8ww1rhl

**Comment by Theolodewijk** [comment]
Sorry but I hate your site, only popups and stupid everywhere hidden links!

**Comment by sitexw** [comment]
For my part, everything works on Firefox (I do not have AdBlock installed).
![image](https://cloud.githubusercontent.com/assets/2950561/19627985/1d4d4d0e-9954-11e6-89da-f46a975ce657.png)
No Javascript errors concerns the file "ablock.js" (which contains FuckAdBlock).

**Comment by e7o-de** [comment]
No, your adblock script is included, that's the problem. It gets loaded, but doesn't check for an adblocker, it just checks if the other scripts from some random tracking networks were loaded. To only block adblock, there would be a check required which actually checks for elements with same origin being filtered, or you should call it "FuckPrivacy" or so.

Actually, not sure why Firefox enabes Tracking Protection just for some users. privacy.trackingprotection.enabled is still false on my Firefox installation and I'm not in private mode (just don't saving any history), must be a different setting which I cannot find right now.
