### ISSUE TITLE
Triple equal operator needed

### ISSUE THREAD

**Issue by RicardoGeek** [sitexw/FuckAdBlock#62]
You need a triple equals here:

https://github.com/sitexw/FuckAdBlock/blob/master/fuckadblock.js#L148

and in the lines below it.

:)

**Comment by sitexw** [comment]
(Je suis désolé pour le temps de réponse)
Quant au «triple égal», je ne préfère pas toucher trop, car dans certains (que je ne sais pas), il pourrait changer le résultat de la détection.
Donc, comme mesure de sécurité, je ne le toucherais pas. Mais le V4 pourrait hériter de ce changement.
