### ISSUE TITLE
NotFoundError: Node was not found

### ISSUE THREAD

**Issue by avdeev** [sitexw/FuckAdBlock#63]
```
/js/application-cd7f4ede96.js in l/this.stop at line 18:22204
/js/application-cd7f4ede96.js in a/this.check/l at line 18:19773
/js/application-cd7f4ede96.js in a/this.check/d< at line 18:20347
/js/application-cd7f4ede96.js in n at line 28:18683
```

reproduced in Firefox and Firefox Mobile

![image](https://cloud.githubusercontent.com/assets/1241671/22819183/0678313c-ef82-11e6-8dfd-31d939b7f42c.png)

**Comment by sitexw** [comment]
Hello, I can not recreate the error in Firefox and the error lines do not match with the FuckAdBlock file.
Do you have a site to show me as an example?

**Comment by avdeev** [comment]
No, i got this error from Sentry

I think the error in this method
https://github.com/sitexw/FuckAdBlock/blob/v4.x/fuckadblock.js#L323
