### ISSUE TITLE
Now AdBlock block FuckAdBlock

### ISSUE THREAD

**Issue by Xpycts** [sitexw/FuckAdBlock#64]
Hello,
this JS library now blocking in Chrome, it's began about month ago

**Comment by sitexw** [comment]
That is to say ?

**Comment by Xpycts** [comment]
AdBlock in my Chrome browser block FuckAdBlock script and he not work. 
After rename js file from fuckadblock.js to checker.js all looks fine.
I think this issues can be closed, but shold keep in mind this problem.

**Comment by sitexw** [comment]
Follow this example code, it works:
https://github.com/sitexw/FuckAdBlock#code-example

If the fuckadblock.js file is not loaded, the FuckAdBlock and fuckAdBlock variables do not exist, so it means that adblock is present.

**Comment by Xpycts** [comment]
I'm use same code from code example by link
Enabled AdBlock plugin block fuckadblock.js by file name when page load, I see this in browser console. Script load again only after I rename it =)
