### ISSUE TITLE
Your bad forcer!!!! Shut up - you're bad killer again Adblock.

### ISSUE THREAD

**Issue by sourceskyboxer** [sitexw/FuckAdBlock#65]
Hello I catch you about unknown evasion again enabled AdBlock. I know now you are liar because you have given many German newspapers website like Bild.de, Suedkurier.de and more Why do you ruin my German newspapers websites. I will hold you if I have time to kill to fuckadblock. Bye bye

And you're really bad munderer again AdBlockers :(

**Comment by AhsanE** [comment]
lol

**Comment by sitexw** [comment]
Have a good day.

**Comment by sourceskyboxer** [comment]
Thanks I want unblock for Adblock because I am always sensitive to hidden spots of hackers or scammers want make dangerous adverts ( like embedded javascript or flash with hidden callback )

That is why it's really dangerous. I wish my computer stays safe. That is why shut up killers! :D I want let to work adblock and Adblock loves your dick. ^^! Adblock holds again bad adverts...
