### ISSUE TITLE
Can't detect FuckFuckAdBlock

### ISSUE THREAD

**Issue by TRGReal** [sitexw/FuckAdBlock#68]
Please fix this, if you do than website creators will be very happy.

**Comment by sitexw** [comment]
It is very easy to FuckFuckFuckAdBlock =)
I have modified the documentation to put forward a more robust FuckAdBlock setup to this kind of script and advertising blocker.
Tell me what you think :
https://github.com/sitexw/FuckAdBlock/tree/f2647f7f61f01c6b3dd0e361ea5acba664aef807#code-example
