### ISSUE TITLE
Remove auto-instantiating

### ISSUE THREAD

**Issue by ViieeS** [sitexw/FuckAdBlock#71]
I think it isn't right behaviour because we need to configure  it after loading anyway.

**Comment by sitexw** [comment]
For now, I prefer to keep this mechanism (albeit a bit old) for the sake of compatibility with previous versions. In addition, a new version will be released using the AMD and CommonJS system that does not instantiate FuckAdBlock automatically (sitexw/FuckAdBlock#77).
