### ISSUE TITLE
False positive during usage of HTTPSEverywhere

### ISSUE THREAD

**Issue by guerda** [sitexw/FuckAdBlock#76]
I found a small issue with FuckAdBlock during the usage of HTTPSEverywhere. Can this be fixed here?

h1. Steps to reproduce
1. Install [HTTPSEverywhere](https://addons.mozilla.org/de/firefox/addon/https-everywhere/) for Firefox in a clean profile
2. Visit [Spiegel.de](http://www.spiegel.de) which is using FuckAdBlock

h1. Expected behavior
No adblocker warning is displayed

h1. Current behavior
Adblocker warning is shown.

Details: https://twitter.com/alvar_f/status/969162172201930752

**Comment by rchassereau** [comment]
Stop
