### ISSUE TITLE
Don't work on mobile

### ISSUE THREAD

**Issue by sxzero** [sitexw/FuckAdBlock#78]
Hi!

I see that the script isn't working on my mobile phone that use AdAway (https://github.com/AdAway/AdAway)

Can you check please?

**Comment by sitexw** [comment]
Are you talking about the FuckAdBlock V3 or the V4?

**Comment by aflores2324** [comment]
@sitexw  - Does V4 work on mobile? Are there any examples?

**Comment by sitexw** [comment]
@aflores2324 => #85
