### ISSUE TITLE
DELETE THIS FUCKING SCRIPT! USERS MUST DECIDE - WATCH ADS OR NO! #ADAIDS!!!!!

### ISSUE THREAD

**Issue by FUCKFUCKADBLOCK** [sitexw/FuckAdBlock#82]
### FUCK U FUCKING SITEXW IN LATEST UPDATE FUCK FUCKADBLOCK DOESN'T WORK! USERS MUST DECIDE - WATCH ADS OR NO, NOT THAT STUPID SITES!!!! I DISABLED MY ADBLOCK ON ONE OF SHITSITES (SHITSITES - MEANS SITE WITH THAT SHIT) AND THERE ANYWHERE ADS! I CAN'T JUST SEE FUCKING TEXT! ADBLOCK PLUS DOESN'T BLOCKS ADS ON NORMAL SITES - YOU MADE THIS STUPID STUFF FOR SITES WITH MORE ADS, THAN CONTENT!!!! FUCK U AND UR PLUGIN.

**Comment by i1u5** [comment]
We'll need to make another FuckFuckAdblock ;D

**Comment by sitexw** [comment]
It's great, but use the same topic as everyone (sitexw/FuckAdBlock#81).
