### ISSUE TITLE
The real issue is that this exists (Webdevs read this)

### ISSUE THREAD

**Issue by ConstantinePallas** [sitexw/FuckAdBlock#87]
By using this on your site, you are not only alienating your audience and customers, but probably also losing money. Of every person i asked about this (for my own sites), every single person said 2 things:

1.  They Hate Adblock blockers
2.  They Hate Companies that use them

So, in conclusion, if you use this people will lose respect for you and your product.

@sitexw is a horrible "company"  because they thrive off of screwing you and you customers over. I assure you the few pennies lost on people with brain cells is nothing compared to the drop in users you **will** experience.

**Comment by TheBarret** [comment]
i second this. avoid this like the plague, but you can see for yourself how ppl simply don't give a f*, they only have self interest and don't care for anything else. I dont use ad blockers, i use a custom dns blackhole server, they will never be able to detect that. hahahaha

**Comment by sitexw** [comment]
@ConstantinePallas no one forces you to block the entire access of the site ... You can simply post a small message that explains why you need to display advertising.

@TheBarret you just have to try the V4 for detection of DNS blocking and we talk about it again.
