### ISSUE TITLE
fuck you

### ISSUE THREAD

**Issue by asdu5asg6da8sjd** [sitexw/FuckAdBlock#96]
fuck you

**Comment by ghost** [comment]
Yes @sitexw gfy. You are an asshole.

**Comment by sitexw** [comment]
![smiling-face-with-tear](https://github.com/sitexw/FuckAdBlock/assets/2950561/24896838-af8f-4fed-8291-c526adf45978)

**Comment by ghost** [comment]
For real why would you do this shit.
